#!/bin/bash

# Replace fire line in app.ts to turn DEBUG off
ROOT=$(pwd)
REPLACE_STRING="export const DEBUG: boolean = false;"
echo "$(sed "1s/.*/$REPLACE_STRING/" $ROOT/src/constants/app.ts)" > $ROOT/src/constants/app.ts
echo "New app.ts file contents:"
cat $ROOT/src/constants/app.ts
echo
echo

# TODO -> If stored password is empty, ask user to input it

# Create android index file
npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/
echo
echo "Finished creating output..."
echo

# Remove output in mdpi folder
IMG_FOLDER="./android/app/src/main/res/drawable-mdpi"
for FILE in $(ls $IMG_FOLDER)
do
  rm -f "$IMG_FOLDER/$FILE"
done
echo "Finished removing output mdpi files..."
echo

# Create relase APK file in
cd ./android
./gradlew assembleRelease
cd ..
echo "Finished creating release APK..."
echo